sudo: false
language: php
php:
  - 7
  - 5.6
  - 5.5
  - 5.4
install:
  - pear install http2 http_request2 stream_var php_codesniffer
  - phpenv rehash
script:
  - phpcs src
  - cd tests && phpunit .
